name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run linter
        run: yarn lint

      - name: Build extension
        run: yarn build

      - name: Extract version from tag
        id: version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Create extension zip
        run: |
          cd dist
          zip -r ../wrong-us-extension-${{ github.ref_name }}.zip .
          cd ..

      - name: Pack extension to CRX
        uses: cardinalby/webext-buildtools-chrome-crx-action@v2
        with:
          zipFilePath: 'wrong-us-extension-${{ github.ref_name }}.zip'
          crxFilePath: 'wrong-us-extension-${{ github.ref_name }}.crx'
          privateKey: ${{ secrets.CHROME_CRX_PRIVATE_KEY }}

      - name: Generate changelog
        id: changelog
        run: |
          if [ -f CHANGELOG.md ]; then
            echo "CHANGELOG<<EOF" >> $GITHUB_OUTPUT
            awk '/^## \[?'${{ steps.version.outputs.VERSION }}'\]?/{flag=1; next} /^## /{flag=0} flag' CHANGELOG.md >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT
          else
            echo "CHANGELOG=Release ${{ steps.version.outputs.VERSION }}" >> $GITHUB_OUTPUT
          fi

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          name: Wrong Us v${{ steps.version.outputs.VERSION }}
          body: |
            ## Wrong Us - The Internet Imposter v${{ steps.version.outputs.VERSION }}

            ${{ steps.changelog.outputs.CHANGELOG }}

            ### Installation Options

            #### Option 1: Unpacked Extension (Recommended for Development)
            1. Download the `wrong-us-extension-${{ github.ref_name }}.zip` file below
            2. Extract it to a folder
            3. Open Chrome and go to `chrome://extensions/`
            4. Enable "Developer mode" (top right toggle)
            5. Click "Load unpacked" and select the extracted folder

            #### Option 2: CRX Package (Advanced Users)
            1. Download the `wrong-us-extension-${{ github.ref_name }}.crx` file below
            2. Open Chrome and go to `chrome://extensions/`
            3. Enable "Developer mode" (top right toggle)
            4. Drag and drop the `.crx` file onto the extensions page

            ### Features
            - 🔗 **URL Redirection**: Redirect any URL pattern using wildcards or regex
            - 📝 **Text Replacement**: Replace text on webpages in real-time
            - 🎯 **Global On/Off Switch**: Easily enable/disable all functionality
            - 🌐 **Pattern Support**: Both wildcard (*) and regex patterns
            - ⚡ **Instant Changes**: No page refresh required

            ### What's New
            See the full changelog in [CHANGELOG.md](CHANGELOG.md)
          files: |
            wrong-us-extension-${{ github.ref_name }}.zip
            wrong-us-extension-${{ github.ref_name }}.crx
          draft: false
          prerelease: false
          generate_release_notes: false
